[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true


# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
    # Threshold for audio recording
    min_decibels = -45
    # Delay for the user to start speaking in MS
    initial_silence_timeout = 3000
    # Delay for the user to continue speaking in MS. If the user stops speaking for this duration, the recording will stop.
    silence_timeout = 1500
    # Above this duration (MS), the recording will forcefully stop.
    max_duration = 15000
    # Duration of the audio chunks in MS
    chunk_duration = 1000
    # Sample rate of the audio
    sample_rate = 44100

edit_message = true

[UI]
# Name of the assistant.
name = "LegalAI"

# Description of the assistant. This is used for HTML tags.
# description = ""

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"
# Custom CSS file that can be used to customize the UI.
custom_css = '/public/test.css'
# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
# custom_js = "/public/test.js"

# Specify a custom font url.
# custom_font = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"

# Specify a custom meta image url.
custom_meta_image_url = "https://chainlit-cloud.s3.eu-west-3.amazonaws.com/logo/chainlit_banner.png"

# Specify a custom build directory for the frontend.
# This can be used to customize the frontend code.
# Be careful: If this is a relative path, it should not start with a slash.
# custom_build = "./public/build"

[UI.theme]
    default = "dark"

# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]
    background = "#F4F6F9"  # Light grayish-blue background
    paper = "#FFFFFF"  # White cards for contrast

    [UI.theme.light.primary]
        main = "#1D3557"  # Deep Blue for primary buttons & highlights
        dark = "#0F1B2D"  # Dark Navy for hover states
        light = "#A8DADC"  # Light Blue for soft highlights

    [UI.theme.light.text]
        primary = "#212121"  # Dark gray text for readability
        secondary = "#616161"  # Lighter gray for secondary text

# Override default MUI dark theme. (Check theme.ts)
[UI.theme.dark]
    background = "#12171F"  # Dark blue-gray for a professional dark theme
    paper = "#1C2331"  # Slightly lighter shade for cards

    [UI.theme.dark.primary]
        main = "#FFC107"  # Gold for highlights & buttons (symbolizing prestige)
        dark = "#B8860B"  # Darker Gold for hover states
        light = "#FFECB3"  # Soft gold highlight

    [UI.theme.dark.text]
        primary = "#EEEEEE"  # White text for readability
        secondary = "#BDBDBD"  # Lighter gray for subtitles


[meta]
generated_by = "1.1.306"
